### ISSUE TITLE
Your Logic class should not invoke methods from UI

### ISSUE THREAD

**Issue by AlexKap23** [pothigai/QuizMaker#4]
https://github.com/pothigai/QuizMaker/blob/e8ccb6c5149bfb9e958c40724664d19513906122/QuizMaker/QuestionListLogic.cs#L16-L20

Your Logic class should not invoke methods from UI. If there's an interaction with the UI, method should be in the UI. 

Logic class should contain only pure logic/business code and no invocations to the UI whatsoever.

It's okay to be the other way round, like UI invoking Logic. Handle this issue as a template to resolve every issue that is the same.

**Comment by pothigai** [comment]
So can i have a replica of the UI class, inside my logic class?
